# Generated by Django 4.2.5 on 2023-10-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_alter_bb_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[['Купля-продажа', [['b', 'Куплю'], ['s', 'Продам']]], ['Обмен', [['c', 'Обменяю']]]], default='s', max_length=1, verbose_name='Тип'),
        ),
    ]
